### ISSUE TITLE
Arrest Mod edits wrong numbers

### ISSUE THREAD

**Issue by OmegaKrogan** [DreadfullyDespized/ahkgtav#19]
**Describe the bug**
When using the Arrest mod to change the Arrest amount from 75 to 50 on ID 3751 instead of editing the 75 for the amount fo months to arrest for it changes the 75 in the ID from 3751 to 3501 

**To Reproduce**
1. Go to the Ticket Calculator
2. Click on the Unlawful use of Weapon and Possession of a CDS w/Intent to Sell
3. Set Mods to 50 and 1250 or any numbers
4. Look down at the Arrest line and notice it changed the ID number to 3xx1 (xx being the Mod for arrest

**Expected behavior**
I expected it to change then amount of Months to what I asked not the ID number

**Screenshots**
https://imgur.com/a/LP7wSs7 - Before setting Mods
https://imgur.com/a/zPaa7nX - After setting Mods

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Version V9.20200507

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DreadfullyDespized** [comment]
Issue has been mitigated in next version.
https://i.imgur.com/tVfFlva.gifv

**Comment by DreadfullyDespized** [comment]
New version is released.  Check and confirm that the issue is resolved.  Comment on here when it is good.

**Comment by DreadfullyDespized** [comment]
No response on issue opener, closing issue.
